name: Nightly-Image-Build

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  Nightly-Image-Build:
    name: Nightly-Image-${{ matrix.arch }}-PHP${{ matrix.php-versions }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4']
        arch: ['x64', 'aarch64']

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Build Nightly Image"
        run: |
            echo "Publish each updated content to the nightly mirror, package and fix errors in time."